USE rhythm;

# ALTER TABLE profile_image
# MODIFY profile_image_seq INT NOT NULL AUTO_INCREMENT;
#
# ALTER TABLE user
# MODIFY user_seq INT NOT NULL AUTO_INCREMENT;
#
# ALTER TABLE song_rank
# MODIFY song_rank_seq INT NOT NULL AUTO_INCREMENT;
#
# ALTER TABLE song
# MODIFY song_seq INT NOT NULL AUTO_INCREMENT;

INSERT INTO profile_image (profile_image_seq, image_name, description, file_name)
VALUES (1, '1 profile image', '1 image', '1 file name'),
       (2, '2 profile image', '2 image', '2 file name'),
       (3, '3 profile image', '3 image', '3 file name'),
       (4, '4 profile image', '4 image', '4 file name'),
       (5, '5 profile image', '5 image', '5 file name');

INSERT INTO user (user_seq, name, nickname, email, profile_image_seq, gender, password, point)
VALUES (1, 'Han', 'ssafy', 'ssafy@naver.com', 1, 'M', '$2a$10$vssYDJemY9v8AAkwLLwHvu3fDFQERHWzSYRRFg0JnXOsMzfDHPtOS', 0),
       (2, 'hyun', 'hyun', 'abc@gmail.com', 1, 'F', '$2a$10$VFXy93wiuII9frJpYVwkaunhA4yC5.t3PObLeOWDmFSOkif9UUJlG', 0),
       (3, '민국', '민국', 'acd4548@naver.com', 1, 'M', '$2a$10$LPFxF8MpOlHoN.gjdcwGNOyAYwK6UaEYzAlTKupTW7aVCi0dMK5li', 0),
       (4, '강현', '현', 'a@naver.com', 1, 'F', '$2a$10$izEmiiCiWgy7YPeuI0Gn5eBG7Fko0SWugFRyEg3ydJBZYYImnaYW2', 1200),
       (5, '홍유빈', '홍유콩', 'ab@naver.com', 2, 'M', '$2a$10$GnzKA038lOiaZ/dUMOhAiucG7xgs9MVadxTnw1eaY.euum86itJMu', 1000),
       (6, '최재용', '최재드래곤', 'b@naver.com', 3, 'M', '$2a$10$mH8IoINNgYrqwcUaGcCub.5/G8L0R2hWE3zMZdN0CYMEkJSOwH2Nm', 800),
       (7, '최한윤', '최고다한윤', 'bc@naver.com', 3, 'F', '$2a$10$H95InRSRPg1tEW4X/DUu8.pO0NXOl.A7Hqef6iHF.1FF9h7iggsMq', 600),
       (8, '강혀니', '현순', 'z@naver.com', 1, 'F', '$2a$10$YBlzKtNiX4Q/eX2bc2GiKeuy98ie4pXXgjldU80pR7ba.B1kX3OaK', 1100);

INSERT INTO song_rank (song_rank_seq, ranking, singer, title)
VALUES (1,1,'NewJeans','Super Shy'),
       (2,2,'정국','Seven (feat. Latto) - Clean Ver.'),
       (3,3,'NewJeans','ETA'),
       (4,4,'박재정','헤어지자 말해요'),
       (5,5,'(여자)아이들','퀸카 (Queencard)'),
       (6,7,'임영웅','모래 알갱이'),
       (7,6,'IVE (아이브)','I AM'),
       (8,8,'임영웅','사랑은 늘 도망가'),
       (9,9,'LE SSERAFIM (르세라핌)','이브, 프시케 그리고 푸른 수염의 아내'),
       (10,10,'aespa','Spicy'),
       (11,11,'임영웅','우리들의 블루스'),
       (12,12,'Lauv','Steal The Show (From “엘리멘탈”)'),
       (13,13,'임영웅','다시 만날 수 있을까'),
       (14,14,'NewJeans','New Jeans'),
       (15,15,'임영웅','무지개'),
       (16,16,'임영웅','이제 나만 믿어요'),
       (17,17,'임영웅','London Boy'),
       (18,18,'임영웅','Polaroid'),
       (19,19,'임영웅','아버지'),
       (20,20,'임영웅','인생찬가'),
       (21,21,'NewJeans','Hype boy'),
       (22,22,'임영웅','A bientot'),
       (23,23,'LE SSERAFIM (르세라핌)','UNFORGIVEN (feat. Nile Rodgers)'),
       (24,24,'임영웅','손이 참 곱던 그대'),
       (25,25,'임영웅','사랑해 진짜'),
       (26,26,'임영웅','연애편지'),
       (27,27,'IVE (아이브)','Kitsch'),
       (28,28,'정국','Still With You'),
       (29,29,'임영웅','보금자리'),
       (30,30,'NewJeans','Ditto'),
       (31,31,'NewJeans','Cool With You'),
       (32,32,'우디 (Woody)','사막에서 꽃을 피우듯'),
       (33,33,'NCT DREAM','ISTJ'),
       (34,34,'NCT DREAM','Candy'),
       (35,35,'NewJeans','Attention'),
       (36,36,'방탄소년단','Dynamite'),
       (37,37,'NewJeans','OMG'),
       (38,38,'세븐틴 (SEVENTEEN)','손오공'),
       (39,39,'Paul Blanco','Summer (Feat. BE’O (비오))'),
       (40,40,'윤하 (YOUNHA)','사건의 지평선'),
       (41,41,'방탄소년단','Take Two'),
       (42,42,'NCT DREAM','Broken Melodies'),
       (43,43,'방탄소년단','Butter'),
       (44,44,'IVE (아이브)','After LIKE'),
       (45,45,'지민','Like Crazy'),
       (46,46,'지수 (JISOO)','꽃'),
       (47,47,'방탄소년단','봄날'),
       (48,48,'IVE (아이브)','LOVE DIVE'),
       (49,49,'정국','Dreamers [Music from the FIFA World Cup Qatar 2022 Official Soundtrack] (Feat. FIFA Sound)'),
       (50,50,'방탄소년단','I Don\'t Think That I Like Her'),
       (51,51,'Charlie Puth','사람 Pt.2 (feat. 아이유)'),
       (52,52,'Agust D','Permission to Dance'),
       (53,53,'방탄소년단','심(心)'),
       (54,54,'DK(디셈버)','Dangerously'),
       (55,55,'Charlie Puth','The Planet'),
       (56,56,'방탄소년단','파이팅 해야지 (Feat. 이영지)'),
       (57,57,'부석순 (SEVENTEEN)','그중에 그대를 만나'),
       (58,58,'김호중','사랑하지 않아서 그랬어'),
       (59,59,'임한별','ASAP'),
       (60,60,'NewJeans','파랑 (Blue Wave)'),
       (61,61,'NCT DREAM','Teddy Bear'),
       (62,62,'STAYC(스테이씨)','물론'),
       (63,63,'허각','In Bloom'),
       (64,64,'ZEROBASEONE (제로베이스원)','나에게 그대만이'),
       (65,65,'탑현','Cupid'),
       (66,66,'FIFTY FIFTY','잠깐 시간 될까'),
       (67,67,'이무진','여름이 들려 (Summer Comes)'),
       (68,68,'오마이걸 (OH MY GIRL)','사랑인가 봐'),
       (69,69,'멜로망스','on the street (with J. Cole)'),
       (70,70,'j-hope','너의 모든 순간'),
       (71,71,'J. Cole','Like We Just Met'),
       (72,72,'성시경','건물 사이에 피어난 장미 (Rose Blossom)'),
       (73,73,'NCT DREAM','ANTIFRAGILE'),
       (74,74,'H1-KEY (하이키)','Yogurt Shake'),
       (75,75,'LE SSERAFIM (르세라핌)','사랑..그게 뭔데'),
       (76,76,'NCT DREAM','Allergy'),
       (77,77,'지아','첫 키스에 내 심장은 120BPM'),
       (78,78,'(여자)아이들','LIP GLOSS'),
       (79,79,'경서','사실말야내가말야그게그러니까말이야'),
       (80,80,'더보이즈 (THE BOYZ)','당신을 만나'),
       (81,81,'케이시 (Kassy)','취중고백'),
       (82,82,'김호중','Poison (모래성)'),
       (83,83,'송가인','Skateboard'),
       (84,84,'김민석 (멜로망스)','해요 (2022)'),
       (85,85,'NCT DREAM','STAY'),
       (86,86,'NCT DREAM','나의 목소리로'),
       (87,87,'#안녕','Fast Forward'),
       (88,88,'The Kid LAROI','Cream Soda'),
       (89,89,'Justin Bieber','SOS'),
       (90,90,'김호중','Heaven(2023)'),
       (91,91,'전소미','TOMBOY'),
       (92,92,'EXO','다정히 내 이름을 부르면'),
       (93,93,'NCT DREAM','사랑의 바보'),
       (94,94,'임재현','Pretzel (♡)'),
       (95,95,'(여자)아이들','인생은 뷰티풀'),
       (96,96,'경서예지','Monologue'),
       (97,97,'전건호','민들레 (single ver.)'),
       (98,98,'제이세라','애인이 되어줄게요 (Prod. 알고보니, 혼수상태)'),
       (99,99,'NCT DREAM','빛이 나는 사람'),
       (100,100,'김호중','That\'s Hilarious');

INSERT INTO song (song_seq, play_count, singer, title, url)
VALUES (1, 0, 'NewJeans', 'Super Shy', '8-HPStXQ4tY'),
       (2, 0, 'NCT DREAM', 'Candy', 'DalyHh0PYoo'),
       (3, 0, '윤하', '사건의지평선', 'Qj1Gt5z4zxo'),
       (4, 0, '임영웅', '사랑은늘도망가(신사와아가씨OST)', 'fmiEetlCGtA'),
       (5, 0, '이무진', '잠깐시간될까', '8-9iT2Z8CLY');